# Generated by Django 6.0.5 on 2026-05-21 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Busyness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Busynesses',
                'db_table': 'busynesses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'complains',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'education',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('slug_en', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'scopes',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(db_index=True, max_length=255)),
                ('place_of_work', models.CharField(blank=True, max_length=255, null=True)),
                ('work_graphite', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('wages_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wages_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('qualification_requirements', models.TextField(blank=True, null=True)),
                ('duties', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('response_email_notifications', models.BooleanField(default=True)),
                ('only_in_english', models.BooleanField(default=False)),
                ('request_type', models.CharField(blank=True, max_length=50, null=True)),
                ('form_from_file', models.CharField(blank=True, max_length=255, null=True)),
                ('link_online_form', models.CharField(blank=True, max_length=255, null=True)),
                ('moderated', models.BooleanField(db_index=True, default=False)),
                ('draft', models.BooleanField(db_index=True, default=False)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('checking', models.BooleanField(default=False)),
                ('waiting_payment', models.BooleanField(default=False)),
                ('free', models.BooleanField(default=False)),
                ('is_fixed', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('in_priority', models.DateTimeField(blank=True, null=True)),
                ('upped', models.BooleanField(default=False)),
                ('send_notification', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('anonim', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('recreated_at', models.DateTimeField(blank=True, null=True)),
                ('user_updated_at', models.DateTimeField(blank=True, null=True)),
                ('count_view', models.IntegerField(default=0)),
                ('count_response', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('busyness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.busyness')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='resumes.city')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.currency')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.education')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='resumes.language')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.scope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vacancies',
            },
        ),
        migrations.CreateModel(
            name='SavedVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_vacancies', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='vacancies.vacancy')),
            ],
            options={
                'db_table': 'vacancy_user',
            },
        ),
        migrations.CreateModel(
            name='ComplainVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.complain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_complaints', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='vacancies.vacancy')),
            ],
            options={
                'db_table': 'complain_vacancies',
            },
        ),
        migrations.CreateModel(
            name='VacancyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('filename1', models.CharField(blank=True, max_length=255, null=True)),
                ('file1', models.CharField(blank=True, max_length=255, null=True)),
                ('filename2', models.CharField(blank=True, max_length=255, null=True)),
                ('file2', models.CharField(blank=True, max_length=255, null=True)),
                ('filename3', models.CharField(blank=True, max_length=255, null=True)),
                ('file3', models.CharField(blank=True, max_length=255, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_offers', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_responses', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='vacancies.vacancy')),
            ],
            options={
                'db_table': 'vacancy_responses',
            },
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['moderated', 'draft', 'archive'], name='vacancies_moderat_3904dc_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['is_fixed', 'in_priority'], name='vacancies_is_fixe_5bdfb4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedvacancy',
            unique_together={('user', 'vacancy')},
        ),
        migrations.AlterUniqueTogether(
            name='complainvacancy',
            unique_together={('vacancy', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='vacancyresponse',
            unique_together={('vacancy', 'resume', 'user')},
        ),
    ]
