# Generated by Django 6.0.5 on 2026-06-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_scope_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyresponse',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('reviewed', 'Рассмотрен'), ('invited', 'Приглашен на интервью'), ('interviewed', 'Прошел интервью'), ('rejected', 'Отказ'), ('hired', 'Нанят')], default='new', max_length=20),
        ),
    ]
