# Generated by Django 6.0.5 on 2026-06-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancyresponse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='application_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='bonuses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='digital_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='email_notification_frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='key_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_net',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
