# Generated by Django 6.0.5 on 2026-06-30 11:45

from django.db import migrations

def seed_currencies(apps, schema_editor):
    Currency = apps.get_model('vacancies', 'Currency')
    currencies = [
        {'title': 'KGS', 'slug': 'kgs', 'order': 1},
        {'title': 'USD', 'slug': 'usd', 'order': 2},
        {'title': 'RUB', 'slug': 'rub', 'order': 3},
        {'title': 'EUR', 'slug': 'eur', 'order': 4},
        {'title': 'KZT', 'slug': 'kzt', 'order': 5},
    ]
    for curr in currencies:
        Currency.objects.get_or_create(slug=curr['slug'], defaults=curr)

def reverse_seed_currencies(apps, schema_editor):
    Currency = apps.get_model('vacancies', 'Currency')
    Currency.objects.filter(slug__in=['kgs', 'usd', 'rub', 'eur', 'kzt']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_vacancy_application_language_vacancy_bonuses_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_currencies, reverse_seed_currencies),
    ]
