# Generated by Django 6.0.5 on 2026-07-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_seed_currencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='application_language',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='application_languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
