# Generated by Django 6.0.5 on 2026-07-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_remove_vacancy_application_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='posting_language',
            field=models.CharField(choices=[('en', 'ENG'), ('ru', 'РУС'), ('ky', 'КЫР')], default='ru', max_length=2, verbose_name='Язык вакансии'),
        ),
    ]
