# Generated by Django 6.0.5 on 2026-05-21 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complainresume',
            name='complain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.complain'),
        ),
        migrations.AddField(
            model_name='complainresume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institution',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.education'),
        ),
        migrations.AddField(
            model_name='resume',
            name='busyness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='vacancies.busyness'),
        ),
        migrations.AddField(
            model_name='resume',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.citizenship'),
        ),
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='resumes.city'),
        ),
        migrations.AddField(
            model_name='resume',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='vacancies.currency'),
        ),
        migrations.AddField(
            model_name='resume',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='resumes.language'),
        ),
        migrations.AddField(
            model_name='resume',
            name='native_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_resumes', to='resumes.language'),
        ),
        migrations.AddField(
            model_name='resume',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='vacancies.scope'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institution',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='extrainstitutions',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_institutions', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='complainresume',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumelanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.language'),
        ),
        migrations.AddField(
            model_name='resumelanguage',
            name='language_proficiency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.languageproficiency'),
        ),
        migrations.AddField(
            model_name='resumelanguage',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_languages', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumeresponse',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumeresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeresponse',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_responses', to='vacancies.vacancy'),
        ),
        migrations.AddField(
            model_name='savedresume',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='savedresume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='resumes.resume'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['moderated', 'draft'], name='resumes_moderat_eb709e_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['is_fixed', 'in_priority'], name='resumes_is_fixe_763dcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='complainresume',
            unique_together={('resume', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='resumelanguage',
            unique_together={('resume', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='resumeresponse',
            unique_together={('vacancy', 'resume', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='savedresume',
            unique_together={('user', 'resume')},
        ),
    ]
