# Generated by Django 6.0.5 on 2026-06-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='driver_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='driver_license_categories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='has_car',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='ready_for_relocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='ready_for_trips',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='ready_to_start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='schedule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='search_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
