# Generated by Django 6.0.5 on 2026-06-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_driver_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='digital_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
