# Generated by Django 6.0.5 on 2026-07-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_digital_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_ai_translated',
            field=models.BooleanField(default=False),
        ),
    ]
