# Generated by Django 6.0.5 on 2026-05-21 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sname', models.CharField(blank=True, max_length=100, null=True)),
                ('mname', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('show_phone', models.BooleanField(default=False)),
                ('personal_bill', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('network', models.CharField(blank=True, max_length=255, null=True)),
                ('identity', models.CharField(blank=True, max_length=255, null=True)),
                ('activated', models.BooleanField(default=False)),
                ('activation_token', models.CharField(blank=True, max_length=255, null=True)),
                ('activation_request_date', models.DateTimeField(blank=True, null=True)),
                ('personal_bill', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('informed', models.BooleanField(default=False)),
                ('informed_at', models.DateTimeField(blank=True, null=True)),
                ('old_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, choices=[('employers', 'Работодатель'), ('workers', 'Соискатель'), ('admin', 'Администратор')], max_length=20, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('about_company', models.TextField(blank=True, null=True)),
                ('google_map_code', models.TextField(blank=True, null=True)),
                ('fio', models.CharField(blank=True, max_length=255, null=True)),
                ('show_fio', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('show_phone', models.BooleanField(default=False)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('show_site', models.BooleanField(default=False)),
                ('is_leading', models.BooleanField(default=False)),
                ('get_contacts', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('personal_bill', models.CharField(blank=True, max_length=50, null=True)),
                ('hide_info', models.BooleanField(default=False)),
                ('super_hr_type', models.CharField(blank=True, max_length=20, null=True)),
                ('super_start_at', models.DateTimeField(blank=True, null=True)),
                ('super_expired_at', models.DateTimeField(blank=True, null=True)),
                ('free_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.city')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
