# Generated by Django 6.0.5 on 2026-06-23 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='org_type',
            field=models.CharField(blank=True, choices=[('ОсОО', 'ОсОО'), ('ЗАО', 'ЗАО'), ('ОАО', 'ОАО'), ('ИП', 'ИП'), ('Представительство / Филиал', 'Представительство / Филиал'), ('НКО', 'НКО'), ('Международная организация', 'Международная организация'), ('Государственная организация', 'Государственная организация')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.CharField(blank=True, choices=[('1-5', '1–5 сотрудников'), ('6-20', '6–20 сотрудников'), ('21-50', '21–50 сотрудников'), ('51-200', '51–200 сотрудников'), ('200+', 'Более 200 сотрудников')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.city'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_status',
            field=models.CharField(blank=True, choices=[('active', 'Активно ищу работу'), ('considering', 'Рассматриваю предложения'), ('not_looking', 'Пока не ищу работу')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main_hr', 'Основной HR'), ('hr_manager', 'HR-менеджер'), ('recruiter', 'Рекрутер')], default='hr_manager', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_employees',
                'unique_together': {('company', 'user')},
            },
        ),
    ]
