# Generated by Django 6.0.5 on 2026-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_company_inn_company_is_verified_company_org_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
    ]
