# Generated by Django 6.0.5 on 2026-06-24 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_company_email_company_show_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='invite_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Подтвержден')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
