# Generated by Django 6.0.5 on 2026-06-26 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_companyemployee_email_companyemployee_invite_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to='users.company')),
            ],
            options={
                'verbose_name': 'Заявка на верификацию',
                'verbose_name_plural': 'Заявки на верификацию',
                'db_table': 'company_verification_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
