# Generated by Django 6.0.5 on 2026-06-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_company_verification_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyverificationrequest',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/', verbose_name='Логотип/Документ'),
        ),
    ]
