# Generated by Django 6.0.5 on 2026-06-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_companyverificationrequest_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyVerificationRequest',
        ),
    ]
