# Generated by Django 6.0.5 on 2026-05-21 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billinglog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilnikpayment',
            name='billing_account_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilnik_billed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilnikpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilnik_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='billing_account_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='billinglog',
            index=models.Index(fields=['billable_id', 'billable_type'], name='billing_log_billabl_ceae33_idx'),
        ),
        migrations.AddIndex(
            model_name='billinglog',
            index=models.Index(fields=['user', 'created_at'], name='billing_log_user_id_3e69de_idx'),
        ),
    ]
